name: $(version)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: S3Bucket
  - name: buildConfiguration
    value: 'Release'
  - name: major
    value: 8
  - name: minor
    value: 0
  - name: version
    value: $[format('{0}.{1}.{2}', variables['major'], variables['minor'], counter(format('{0}.{1}', variables['major'], variables['minor']), 0))]


steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 5.0.x'
  inputs:
    packageType: sdk
    version: '5.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: 'e5fb2e9c-1207-48a4-8f7b-2e6b32308210'


- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
  
- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Replace tokens'
  inputs:
    targetFiles: |
      **/*.json

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: pack
    packagesToPack: 'SW.CloudFiles.S3/SW.CloudFiles.S3.csproj;SW.CloudFiles.S3.Extensions/SW.CloudFiles.S3.Extensions.csproj;SW.CloudFiles.AS/SW.CloudFiles.AS.csproj;SW.CloudFiles.OC/SW.CloudFiles.OC.csproj;SW.CloudFiles.AS.Extensions/SW.CloudFiles.AS.Extensions.csproj;SW.CloudFiles.OC.Extensions/SW.CloudFiles.OC.Extensions.csproj'
    nobuild: true
    versioningScheme: byBuildNumber

- task: NuGetCommand@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'swnuget' 

